name: cloud9
description: A Flutter package for integrating with popular cloud storage services such as Dropbox, Google Drive, and OneDrive.
version: 0.0.1-Dev
homepage: https://github.com/Yczar/cloud9

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  dio: ">=4.0.6 <6.0.0"
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.4.0
  http: ^0.13.5
  oauth2: ^2.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
